name: "Build"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start service containers
        run: docker-compose -f docker/test-services.yml up -d
      - name: Ensure .NET is installed
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Detect Version
        run: |
          $ref = '${{ github.ref }}'
          if ($ref.StartsWith('refs/tags/v'))
          {
              $version = ($ref -split '/v' | Select-Object -Last 1)
          }
          else
          {
              $version = "0.0.1"
          }
          Write-Host "Detected version: '$version'."
          "BUILD_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Build and pack
        run: |
          dotnet build -c Release  -p:Version=$BUILD_VERSION
          dotnet pack -c Release -p:Version=$BUILD_VERSION -o ./publish

      - name: Run functional tests
        run: |
          dotnet test -c Release  -p:Version=$BUILD_VERSION

      - name: Stop service containers
        if: always()
        run: docker-compose -f docker/test-services.yml down

      - name: Publish
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/q6tech/index.json"